version: '3.8'
services:
  app:
    image: grocery-booking-app
    build: .
    ports:
      - "8081:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/grocerybooking
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    depends_on:
      - mysql

  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: grocerybooking
    ports:
      - "3307:3306"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge


